export type IData = {
  ID: string
  /** 父级id */
  Pid?: string
  /** 名称 */
  Name?: string
  /** 应用图标 */
  Icon?: string
  /** 功能描述 */
  FuncDes?: string
  /** 变更内容 */
  UpdateInfo?: string
  /** 开发者 */
  Developer?: string
  /** 创建时间 */
  CreateTime?: string
  /** 应用脚本 */
  Obj?: any
  /** 排序 */
  Sort?: string
  /** 修改人 */
  ModifyBy?: string
  /** 修改时间 */
  ModifyTime?: string
  /** 下载次数 */
  DownloadCount?: number
}

// export const tableData: IData[] = []
export const tableData: IData[] = [
  {
    ID: '1',
    Pid: '0',
    Name: '应用一',
    Icon: 'edit', // 示例图标
    FuncDes:
      '这是一个详细的功能描述，它包含了关于这个应用的各种信息和细节，帮助用户更好地了解项目的内容。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '修复了一些已知问题并优化了性能。',
    Developer: '张三',
    CreateTime: '2023-01-01',
    Obj: '{}',
    Sort: '1',
    ModifyBy: '李四',
    ModifyTime: '2023-02-01',
    DownloadCount: 100,
  },
  {
    ID: '2',
    Pid: '0',
    Name: '应用二',
    Icon: 'share',
    FuncDes:
      '这是另一个详细的功能描述，提供了更多的背景信息和相关的使用指南，确保用户能够充分利用该功能。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '增加了新的功能模块。',
    Developer: '王五',
    CreateTime: '2023-01-02',
    Obj: '{}',
    Sort: '2',
    ModifyBy: '赵六',
    ModifyTime: '2023-02-02',
    DownloadCount: 150,
  },
  {
    ID: '3',
    Pid: '0',
    Name: '应用三',
    Icon: 'delete',
    FuncDes:
      '这里有一些详细的信息，包括项目的起源、发展过程以及未来的规划，让用户对项目有一个全面的认识。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '优化了用户界面。',
    Developer: '孙七',
    CreateTime: '2023-01-03',
    Obj: '{}',
    Sort: '3',
    ModifyBy: '周八',
    ModifyTime: '2023-02-03',
    DownloadCount: 200,
  },
  {
    ID: '4',
    Pid: '0',
    Name: '应用四',
    Icon: 'setting',
    FuncDes:
      '这个项目非常有趣，它不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '新增了国际化支持。',
    Developer: '吴九',
    CreateTime: '2023-01-04',
    Obj: '{}',
    Sort: '4',
    ModifyBy: '郑十',
    ModifyTime: '2023-02-04',
    DownloadCount: 250,
  },
  {
    ID: '5',
    Pid: '0',
    Name: '应用五',
    Icon: 'picture',
    FuncDes:
      '这是一个测试项目，尽管它是测试性质的，但依然包含了丰富的功能和详细的文档说明，方便开发者进行调试和学习。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '修复了一些安全漏洞。',
    Developer: '钱十一',
    CreateTime: '2023-01-05',
    Obj: '{}',
    Sort: '5',
    ModifyBy: '刘十二',
    ModifyTime: '2023-02-05',
    DownloadCount: 300,
  },
  {
    ID: '6',
    Pid: '0',
    Name: '应用六',
    Icon: 'search',
    FuncDes:
      '这是一个详细的功能描述，它包含了关于这个应用的各种信息和细节，帮助用户更好地了解项目的内容。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '优化了性能。',
    Developer: '陈十三',
    CreateTime: '2023-01-06',
    Obj: '{}',
    Sort: '6',
    ModifyBy: '杨十四',
    ModifyTime: '2023-02-06',
    DownloadCount: 350,
  },
  {
    ID: '7',
    Pid: '0',
    Name: '应用七',
    Icon: 'star-off',
    FuncDes:
      '这是另一个详细的功能描述，提供了更多的背景信息和相关的使用指南，确保用户能够充分利用该功能。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '增加了新的功能模块。',
    Developer: '黄十五',
    CreateTime: '2023-01-07',
    Obj: '{}',
    Sort: '7',
    ModifyBy: '徐十六',
    ModifyTime: '2023-02-07',
    DownloadCount: 400,
  },
  {
    ID: '8',
    Pid: '0',
    Name: '应用八',
    Icon: 'upload',
    FuncDes:
      '这里有一些详细的信息，包括项目的起源、发展过程以及未来的规划，让用户对项目有一个全面的认识。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '优化了用户界面。',
    Developer: '何十七',
    CreateTime: '2023-01-08',
    Obj: '{}',
    Sort: '8',
    ModifyBy: '朱十八',
    ModifyTime: '2023-02-08',
    DownloadCount: 450,
  },
  {
    ID: '9',
    Pid: '0',
    Name: '应用九',
    Icon: 'download',
    FuncDes:
      '这个项目非常有趣，它不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '新增了国际化支持。',
    Developer: '尤十九',
    CreateTime: '2023-01-09',
    Obj: '{}',
    Sort: '9',
    ModifyBy: '秦二十',
    ModifyTime: '2023-02-09',
    DownloadCount: 500,
  },
  {
    ID: '10',
    Pid: '0',
    Name: '应用十',
    Icon: 'check',
    FuncDes:
      '这是一个测试项目，尽管它是测试性质的，但依然包含了丰富的功能和详细的文档说明，方便开发者进行调试和学习。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '修复了一些安全漏洞。',
    Developer: '许二十一',
    CreateTime: '2023-01-10',
    Obj: '{}',
    Sort: '10',
    ModifyBy: '何二十二',
    ModifyTime: '2023-02-10',
    DownloadCount: 550,
  },
  {
    ID: '11',
    Pid: '0',
    Name: '应用十一',
    Icon: 'message',
    FuncDes:
      '这是一个详细的功能描述，它包含了关于这个应用的各种信息和细节，帮助用户更好地了解项目的内容。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '优化了性能。',
    Developer: '施二十三',
    CreateTime: '2023-01-11',
    Obj: '{}',
    Sort: '11',
    ModifyBy: '孔二十四',
    ModifyTime: '2023-02-11',
    DownloadCount: 600,
  },
  {
    ID: '12',
    Pid: '0',
    Name: '应用十二',
    Icon: 'date',
    FuncDes:
      '这是另一个详细的功能描述，提供了更多的背景信息和相关的使用指南，确保用户能够充分利用该功能。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '增加了新的功能模块。',
    Developer: '常二十五',
    CreateTime: '2023-01-12',
    Obj: '{}',
    Sort: '12',
    ModifyBy: '严二十六',
    ModifyTime: '2023-02-12',
    DownloadCount: 650,
  },
  {
    ID: '13',
    Pid: '0',
    Name: '应用十三',
    Icon: 'zoom-in',
    FuncDes:
      '这里有一些详细的信息，包括项目的起源、发展过程以及未来的规划，让用户对项目有一个全面的认识。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '优化了用户界面。',
    Developer: '华二十七',
    CreateTime: '2023-01-13',
    Obj: '{}',
    Sort: '13',
    ModifyBy: '金二十八',
    ModifyTime: '2023-02-13',
    DownloadCount: 700,
  },
  {
    ID: '14',
    Pid: '0',
    Name: '应用十四',
    Icon: 'refresh',
    FuncDes:
      '这个项目非常有趣，它不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '新增了国际化支持。',
    Developer: '陶二十九',
    CreateTime: '2023-01-14',
    Obj: '{}',
    Sort: '14',
    ModifyBy: '邱三十',
    ModifyTime: '2023-02-14',
    DownloadCount: 750,
  },
  {
    ID: '15',
    Pid: '0',
    Name: '应用十五',
    Icon: 'more',
    FuncDes:
      '这是一个测试项目，尽管它是测试性质的，但依然包含了丰富的功能和详细的文档说明，方便开发者进行调试和学习。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '修复了一些安全漏洞。',
    Developer: '谢三十一',
    CreateTime: '2023-01-15',
    Obj: '{}',
    Sort: '15',
    ModifyBy: '章三十二',
    ModifyTime: '2023-02-15',
    DownloadCount: 800,
  },
  {
    ID: '16',
    Pid: '0',
    Name: '应用十六',
    Icon: 'menu',
    FuncDes:
      '这是一个详细的功能描述，它包含了关于这个应用的各种信息和细节，帮助用户更好地了解项目的内容。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '优化了性能。',
    Developer: '汪三十三',
    CreateTime: '2023-01-16',
    Obj: '{}',
    Sort: '16',
    ModifyBy: '余三十四',
    ModifyTime: '2023-02-16',
    DownloadCount: 850,
  },
  {
    ID: '17',
    Pid: '0',
    Name: '应用十七',
    Icon: 'document',
    FuncDes:
      '这是另一个详细的功能描述，提供了更多的背景信息和相关的使用指南，确保用户能够充分利用该功能。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '增加了新的功能模块。',
    Developer: '毕三十五',
    CreateTime: '2023-01-17',
    Obj: '{}',
    Sort: '17',
    ModifyBy: '尹三十六',
    ModifyTime: '2023-02-17',
    DownloadCount: 900,
  },
  {
    ID: '18',
    Pid: '0',
    Name: '应用十八',
    Icon: 'folder',
    FuncDes:
      '这里有一些详细的信息，包括项目的起源、发展过程以及未来的规划，让用户对项目有一个全面的认识。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '优化了用户界面。',
    Developer: '康三十七',
    CreateTime: '2023-01-18',
    Obj: '{}',
    Sort: '18',
    ModifyBy: '邓三十八',
    ModifyTime: '2023-02-18',
    DownloadCount: 950,
  },
  {
    ID: '19',
    Pid: '0',
    Name: '应用十九',
    Icon: 'tickets',
    FuncDes:
      '这个项目非常有趣，它不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '新增了国际化支持。',
    Developer: '安三十九',
    CreateTime: '2023-01-19',
    Obj: '{}',
    Sort: '19',
    ModifyBy: '顾四十',
    ModifyTime: '2023-02-19',
    DownloadCount: 1000,
  },
  {
    ID: '20',
    Pid: '0',
    Name: '应用二十',
    Icon: 'bell',
    FuncDes:
      '这是一个测试项目，尽管它是测试性质的，但依然包含了丰富的功能和详细的文档说明，方便开发者进行调试和学习。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '修复了一些安全漏洞。',
    Developer: '柳四十一',
    CreateTime: '2023-01-20',
    Obj: '{}',
    Sort: '20',
    ModifyBy: '段四十二',
    ModifyTime: '2023-02-20',
    DownloadCount: 1050,
  },
  {
    ID: '21',
    Pid: '0',
    Name: '应用二十一',
    Icon: 'news',
    FuncDes:
      '这是一个详细的功能描述，它包含了关于这个应用的各种信息和细节，帮助用户更好地了解项目的内容。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '优化了性能。',
    Developer: '叶四十三',
    CreateTime: '2023-01-21',
    Obj: '{}',
    Sort: '21',
    ModifyBy: '熊四十四',
    ModifyTime: '2023-02-21',
    DownloadCount: 1100,
  },
  {
    ID: '22',
    Pid: '0',
    Name: '应用二十二',
    Icon: 'view',
    FuncDes:
      '这是另一个详细的功能描述，提供了更多的背景信息和相关的使用指南，确保用户能够充分利用该功能。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '增加了新的功能模块。',
    Developer: '贺四十五',
    CreateTime: '2023-01-22',
    Obj: '{}',
    Sort: '22',
    ModifyBy: '隋四十六',
    ModifyTime: '2023-02-22',
    DownloadCount: 1150,
  },
  {
    ID: '23',
    Pid: '0',
    Name: '应用二十三',
    Icon: 'video-camera',
    FuncDes:
      '这里有一些详细的信息，包括项目的起源、发展过程以及未来的规划，让用户对项目有一个全面的认识。该应用不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。',
    UpdateInfo: '优化了用户界面。',
    Developer: '尹四十七',
    CreateTime: '2023-01-23',
    Obj: '{}',
    Sort: '23',
    ModifyBy: '骆四十八',
    ModifyTime: '2023-02-23',
    DownloadCount: 1200,
  },
  {
    ID: '24',
    Pid: '0',
    Name: '应用二十四',
    Icon: 'mobile-phone',
    FuncDes:
      '这个项目非常有趣，它不仅提供了一些基础的功能，还引入了许多创新的设计理念，极大地提升了用户体验。该应用提供了丰富的功能和详细的文档说明，方便开发者进行调试和学习。',
    UpdateInfo: '新增了国际化支持。',
    Developer: '薛四十九',
    CreateTime: '2023-01-24',
    Obj: '{}',
    Sort: '24',
    ModifyBy: '郦五十',
    ModifyTime: '2023-02-24',
    DownloadCount: 854,
  },
]
